//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.03 at 12:11:27 PM EAT 
//


package com.example.camelone.schemas.exact;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.camelone.schemas.exact package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierCustSupID_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "custSupID");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierCustSuperID_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "custSuperID");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierCustSupName_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "custSupName");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierContact_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "contact");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierTelephone_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "telephone");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierWebsite_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "website");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierCommerceNr_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "commerceNr");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierEMail_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "eMail");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierTaxRegistrationCountry_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "taxRegistrationCountry");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierCustSupTp_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "custSupTp");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierStreetAddress_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "streetAddress");
    private final static QName _AuditfileCompanyCustomersSuppliersCustomerSupplierBankAccount_QNAME = new QName("http://www.auditfiles.nl/XAF/3.2", "bankAccount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.camelone.schemas.exact
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Auditfile }
     * 
     */
    public Auditfile createAuditfile() {
        return new Auditfile();
    }

    /**
     * Create an instance of {@link Auditfile.Company }
     * 
     */
    public Auditfile.Company createAuditfileCompany() {
        return new Auditfile.Company();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions }
     * 
     */
    public Auditfile.Company.Transactions createAuditfileCompanyTransactions() {
        return new Auditfile.Company.Transactions();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions.Subledgers }
     * 
     */
    public Auditfile.Company.Transactions.Subledgers createAuditfileCompanyTransactionsSubledgers() {
        return new Auditfile.Company.Transactions.Subledgers();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions.Subledgers.Subledger }
     * 
     */
    public Auditfile.Company.Transactions.Subledgers.Subledger createAuditfileCompanyTransactionsSubledgersSubledger() {
        return new Auditfile.Company.Transactions.Subledgers.Subledger();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions.Journal }
     * 
     */
    public Auditfile.Company.Transactions.Journal createAuditfileCompanyTransactionsJournal() {
        return new Auditfile.Company.Transactions.Journal();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions.Journal.Transaction }
     * 
     */
    public Auditfile.Company.Transactions.Journal.Transaction createAuditfileCompanyTransactionsJournalTransaction() {
        return new Auditfile.Company.Transactions.Journal.Transaction();
    }

    /**
     * Create an instance of {@link Auditfile.Company.OpeningBalance }
     * 
     */
    public Auditfile.Company.OpeningBalance createAuditfileCompanyOpeningBalance() {
        return new Auditfile.Company.OpeningBalance();
    }

    /**
     * Create an instance of {@link Auditfile.Company.OpeningBalance.ObSubledgers }
     * 
     */
    public Auditfile.Company.OpeningBalance.ObSubledgers createAuditfileCompanyOpeningBalanceObSubledgers() {
        return new Auditfile.Company.OpeningBalance.ObSubledgers();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Periods }
     * 
     */
    public Auditfile.Company.Periods createAuditfileCompanyPeriods() {
        return new Auditfile.Company.Periods();
    }

    /**
     * Create an instance of {@link Auditfile.Company.VatCodes }
     * 
     */
    public Auditfile.Company.VatCodes createAuditfileCompanyVatCodes() {
        return new Auditfile.Company.VatCodes();
    }

    /**
     * Create an instance of {@link Auditfile.Company.GeneralLedger }
     * 
     */
    public Auditfile.Company.GeneralLedger createAuditfileCompanyGeneralLedger() {
        return new Auditfile.Company.GeneralLedger();
    }

    /**
     * Create an instance of {@link Auditfile.Company.GeneralLedger.Basics }
     * 
     */
    public Auditfile.Company.GeneralLedger.Basics createAuditfileCompanyGeneralLedgerBasics() {
        return new Auditfile.Company.GeneralLedger.Basics();
    }

    /**
     * Create an instance of {@link Auditfile.Company.CustomersSuppliers }
     * 
     */
    public Auditfile.Company.CustomersSuppliers createAuditfileCompanyCustomersSuppliers() {
        return new Auditfile.Company.CustomersSuppliers();
    }

    /**
     * Create an instance of {@link Auditfile.Company.CustomersSuppliers.CustomerSupplier }
     * 
     */
    public Auditfile.Company.CustomersSuppliers.CustomerSupplier createAuditfileCompanyCustomersSuppliersCustomerSupplier() {
        return new Auditfile.Company.CustomersSuppliers.CustomerSupplier();
    }

    /**
     * Create an instance of {@link Auditfile.Header }
     * 
     */
    public Auditfile.Header createAuditfileHeader() {
        return new Auditfile.Header();
    }

    /**
     * Create an instance of {@link Auditfile.Company.StreetAddress }
     * 
     */
    public Auditfile.Company.StreetAddress createAuditfileCompanyStreetAddress() {
        return new Auditfile.Company.StreetAddress();
    }

    /**
     * Create an instance of {@link Auditfile.Company.PostalAddress }
     * 
     */
    public Auditfile.Company.PostalAddress createAuditfileCompanyPostalAddress() {
        return new Auditfile.Company.PostalAddress();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions.Subledgers.Subledger.SbLine }
     * 
     */
    public Auditfile.Company.Transactions.Subledgers.Subledger.SbLine createAuditfileCompanyTransactionsSubledgersSubledgerSbLine() {
        return new Auditfile.Company.Transactions.Subledgers.Subledger.SbLine();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Transactions.Journal.Transaction.TrLine }
     * 
     */
    public Auditfile.Company.Transactions.Journal.Transaction.TrLine createAuditfileCompanyTransactionsJournalTransactionTrLine() {
        return new Auditfile.Company.Transactions.Journal.Transaction.TrLine();
    }

    /**
     * Create an instance of {@link Auditfile.Company.OpeningBalance.ObSubledgers.ObSubledger }
     * 
     */
    public Auditfile.Company.OpeningBalance.ObSubledgers.ObSubledger createAuditfileCompanyOpeningBalanceObSubledgersObSubledger() {
        return new Auditfile.Company.OpeningBalance.ObSubledgers.ObSubledger();
    }

    /**
     * Create an instance of {@link Auditfile.Company.Periods.Period }
     * 
     */
    public Auditfile.Company.Periods.Period createAuditfileCompanyPeriodsPeriod() {
        return new Auditfile.Company.Periods.Period();
    }

    /**
     * Create an instance of {@link Auditfile.Company.VatCodes.VatCode }
     * 
     */
    public Auditfile.Company.VatCodes.VatCode createAuditfileCompanyVatCodesVatCode() {
        return new Auditfile.Company.VatCodes.VatCode();
    }

    /**
     * Create an instance of {@link Auditfile.Company.GeneralLedger.LedgerAccount }
     * 
     */
    public Auditfile.Company.GeneralLedger.LedgerAccount createAuditfileCompanyGeneralLedgerLedgerAccount() {
        return new Auditfile.Company.GeneralLedger.LedgerAccount();
    }

    /**
     * Create an instance of {@link Auditfile.Company.GeneralLedger.Basics.Basic }
     * 
     */
    public Auditfile.Company.GeneralLedger.Basics.Basic createAuditfileCompanyGeneralLedgerBasicsBasic() {
        return new Auditfile.Company.GeneralLedger.Basics.Basic();
    }

    /**
     * Create an instance of {@link Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress }
     * 
     */
    public Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress createAuditfileCompanyCustomersSuppliersCustomerSupplierStreetAddress() {
        return new Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress();
    }

    /**
     * Create an instance of {@link Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount }
     * 
     */
    public Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount createAuditfileCompanyCustomersSuppliersCustomerSupplierBankAccount() {
        return new Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "custSupID", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<Integer> createAuditfileCompanyCustomersSuppliersCustomerSupplierCustSupID(Integer value) {
        return new JAXBElement<Integer>(_AuditfileCompanyCustomersSuppliersCustomerSupplierCustSupID_QNAME, Integer.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "custSuperID", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<Integer> createAuditfileCompanyCustomersSuppliersCustomerSupplierCustSuperID(Integer value) {
        return new JAXBElement<Integer>(_AuditfileCompanyCustomersSuppliersCustomerSupplierCustSuperID_QNAME, Integer.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "custSupName", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierCustSupName(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierCustSupName_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "contact", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierContact(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierContact_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "telephone", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierTelephone(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierTelephone_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "website", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierWebsite(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierWebsite_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "commerceNr", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<Long> createAuditfileCompanyCustomersSuppliersCustomerSupplierCommerceNr(Long value) {
        return new JAXBElement<Long>(_AuditfileCompanyCustomersSuppliersCustomerSupplierCommerceNr_QNAME, Long.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "eMail", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierEMail(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierEMail_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "taxRegistrationCountry", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierTaxRegistrationCountry(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierTaxRegistrationCountry_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "custSupTp", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<String> createAuditfileCompanyCustomersSuppliersCustomerSupplierCustSupTp(String value) {
        return new JAXBElement<String>(_AuditfileCompanyCustomersSuppliersCustomerSupplierCustSupTp_QNAME, String.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "streetAddress", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress> createAuditfileCompanyCustomersSuppliersCustomerSupplierStreetAddress(Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress value) {
        return new JAXBElement<Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress>(_AuditfileCompanyCustomersSuppliersCustomerSupplierStreetAddress_QNAME, Auditfile.Company.CustomersSuppliers.CustomerSupplier.StreetAddress.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.auditfiles.nl/XAF/3.2", name = "bankAccount", scope = Auditfile.Company.CustomersSuppliers.CustomerSupplier.class)
    public JAXBElement<Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount> createAuditfileCompanyCustomersSuppliersCustomerSupplierBankAccount(Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount value) {
        return new JAXBElement<Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount>(_AuditfileCompanyCustomersSuppliersCustomerSupplierBankAccount_QNAME, Auditfile.Company.CustomersSuppliers.CustomerSupplier.BankAccount.class, Auditfile.Company.CustomersSuppliers.CustomerSupplier.class, value);
    }

}
