//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.03 at 12:11:27 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.auditfiles.nl/XAF/3.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.camelone.schemas.exact;
